//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EshtryFrontend.LoginRegisterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginRegisterService.LoginAndRegister")]
    public interface LoginAndRegister {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAndRegister/DoWork", ReplyAction="http://tempuri.org/LoginAndRegister/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAndRegister/DoWork", ReplyAction="http://tempuri.org/LoginAndRegister/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAndRegister/Register", ReplyAction="http://tempuri.org/LoginAndRegister/RegisterResponse")]
        bool Register(string username, string password, int age, string gender, string address, string phonenumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAndRegister/Register", ReplyAction="http://tempuri.org/LoginAndRegister/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string username, string password, int age, string gender, string address, string phonenumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAndRegister/Login", ReplyAction="http://tempuri.org/LoginAndRegister/LoginResponse")]
        int Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAndRegister/Login", ReplyAction="http://tempuri.org/LoginAndRegister/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginAndRegisterChannel : EshtryFrontend.LoginRegisterService.LoginAndRegister, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginAndRegisterClient : System.ServiceModel.ClientBase<EshtryFrontend.LoginRegisterService.LoginAndRegister>, EshtryFrontend.LoginRegisterService.LoginAndRegister {
        
        public LoginAndRegisterClient() {
        }
        
        public LoginAndRegisterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginAndRegisterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginAndRegisterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginAndRegisterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool Register(string username, string password, int age, string gender, string address, string phonenumber, string email) {
            return base.Channel.Register(username, password, age, gender, address, phonenumber, email);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string username, string password, int age, string gender, string address, string phonenumber, string email) {
            return base.Channel.RegisterAsync(username, password, age, gender, address, phonenumber, email);
        }
        
        public int Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
    }
}
